# Generated by Django 4.2.23 on 2025-09-02 04:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_TAKEN', '미수강'), ('ENROLLED', '수강중'), ('COMPLETED', '수료')], db_index=True, default='NOT_TAKEN', max_length=12)),
                ('completion_rate', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='완성도(%)')),
                ('last_session_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 학습 시각')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='organizations.employee')),
            ],
            options={
                'verbose_name': '수강',
                'verbose_name_plural': '수강',
                'indexes': [models.Index(fields=['employee', 'status'], name='enrollments_employe_a8f049_idx'), models.Index(fields=['course', 'status'], name='enrollments_course__f8877c_idx'), models.Index(fields=['-updated_at'], name='enrollments_updated_d20e17_idx')],
                'unique_together': {('employee', 'course')},
            },
        ),
    ]
