# Generated by Django 4.2.23 on 2025-09-03 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_employe_a8f049_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_course__f8877c_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_updated_d20e17_idx',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='completion_rate',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_session_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='updated_at',
        ),
    ]
