# Generated by Django 4.2.23 on 2025-09-02 04:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='회사명')),
                ('biz_no', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', '사업자등록번호는 숫자 10자리여야 합니다.')], verbose_name='사업자등록번호')),
                ('domain', models.CharField(blank=True, max_length=120, verbose_name='회사 이메일 도메인')),
            ],
            options={
                'verbose_name': '회사',
                'verbose_name_plural': '회사',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='회사 이메일')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='직책/직무')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사원',
                'verbose_name_plural': '사원',
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='organizatio_name_190560_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['biz_no'], name='organizatio_biz_no_16ea54_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'is_active'], name='organizatio_company_401b07_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'position'], name='organizatio_company_1f4fc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='uniq_employee_per_company'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('company', 'email'), name='uniq_email_per_company'),
        ),
    ]
