# Generated by Django 4.2.23 on 2025-09-03 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='uniq_employee_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='uniq_email_per_company',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='organizatio_name_190560_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='organizatio_biz_no_16ea54_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='organizatio_company_401b07_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='organizatio_company_1f4fc8_idx',
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='company',
            name='biz_no',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', '사업자등록번호는 숫자 10자리여야 합니다.')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
