# Generated by Django 4.2.23 on 2025-09-21 19:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_alter_employee_emp_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_uid', models.CharField(max_length=120)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('api_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_devices', to='organizations.company')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metric', models.CharField(db_index=True, max_length=120)),
                ('value', models.FloatField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='sensor.sensordevice')),
            ],
            options={
                'ordering': ['-ts', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='sensordevice',
            constraint=models.UniqueConstraint(fields=('company', 'device_uid'), name='uq_sensor_device_company_uid'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['device', 'ts'], name='sensor_sens_device__a1a2c7_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['device', 'metric', 'ts'], name='sensor_sens_device__69a0bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='sensordata',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('device', 'idempotency_key'), name='uq_sensor_data_device_idem'),
        ),
    ]
