# Generated by Django 4.2.23 on 2025-09-02 04:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='교육 코드')),
                ('title', models.CharField(max_length=200, verbose_name='교육명')),
                ('description', models.TextField(blank=True, verbose_name='교육 설명')),
                ('duration_min', models.PositiveIntegerField(default=0, verbose_name='권장 소요시간(분)')),
            ],
            options={
                'verbose_name': '교육',
                'verbose_name_plural': '교육',
                'indexes': [models.Index(fields=['code'], name='courses_cou_code_612388_idx'), models.Index(fields=['title'], name='courses_cou_title_6e78a2_idx')],
            },
        ),
    ]
