# Generated by Django 5.2.6 on 2025-09-24 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_remove_userrecording_sensor_data_json_and_more"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="motion_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ai.motiontype",
            ),
        ),
    ]
