# Generated by Django 5.2.6 on 2025-09-22 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("organizations", "0004_alter_employee_emp_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="motiontype",
            name="max_dtw_distance",
            field=models.FloatField(
                default=1000.0, help_text="점수 정규화를 위한 최대 DTW 거리"
            ),
        ),
        migrations.AlterField(
            model_name="userrecording",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="motion_recordings",
                to="organizations.employee",
            ),
        ),
        migrations.CreateModel(
            name="SensorDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("device_uid", models.CharField(max_length=120)),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "api_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_devices",
                        to="organizations.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "device_uid"),
                        name="uq_ai_sensor_device_company_uid",
                    )
                ],
            },
        ),
    ]
