# Generated by Django 5.2.6 on 2025-09-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_motiontype_max_dtw_distance_alter_userrecording_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrecording",
            name="sensor_data_json",
        ),
        migrations.AlterField(
            model_name="sensordevice",
            name="api_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, unique=True
            ),
        ),
    ]
